### ISSUE TITLE
SharedInv - game stuck on loading with this mod enabled

### ISSUE THREAD

**Issue by kkon10** [p1xel8ted/GYK-Harmony1to2-Conversions#1]
Newest version of the game, from GOG, Windows 10. Whenever I enable this mod, the game no longer loads for me. I tried using the config file from the original mod in case this was the source of the issue, but it persists.

![image](https://user-images.githubusercontent.com/107314549/173700956-4aa65277-bd9a-4ed9-81da-8ef2e7f77315.png)

![image](https://user-images.githubusercontent.com/107314549/173701220-f964230c-cd9e-4b07-8e96-36d4702e72d8.png)

![image](https://user-images.githubusercontent.com/107314549/173701025-260fb49f-37d3-44b7-9bec-d07d7f7526ce.png)

**Comment by p1xel8ted** [comment]
It's definitely that mod? even if it's the only mod enabled it still does it? Can you attach Player.log and qmod_reloaded_log.txt please.

**Comment by kkon10** [comment]
Same thing is happening after using this test version both via QMR and directly. Where can I find the player.log file? Thanks 

![image](https://user-images.githubusercontent.com/107314549/173963058-b6f90519-e253-415d-a5ee-213834a3c44a.png)

![image](https://user-images.githubusercontent.com/107314549/173963157-b754d412-bda3-4938-9f7e-267d9b4838a8.png)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Harmony1to2-Conversions/files/8914417/qmod_reloaded_log.txt)

**Comment by p1xel8ted** [comment]
C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper

Please delete both logs (and the QMR log), and test the game again so it generates fresh logs with only relevant entries.

**Comment by Kiorn** [comment]
Try to turn off doCraftFromAnywhere in More Storage

**Comment by p1xel8ted** [comment]
> C:\Users<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper
> 
> Please delete both logs (and the QMR log), and test the game again so it generates fresh logs with only relevant entries.
